spring.application.name=metrics_demo

management.endpoints.web.exposure.include=health, prometheus, metrics
management.endpoints.endpoint.prometheus.enabled=true
management.endpoints.metrics.tags.application=${spring.application.name}